### ISSUE TITLE
Not passing in a query string parameter that is defined results in a 405 error

### ISSUE THREAD

**Issue by akeemphilbert** [wepala/weos#181]
When a query string parameter is defined in the open api specification and a request is made without passing in that query value a 405 method not allowed error is returned. What should happen instead is a 400 bad request error is returned IF the query string parameter is required. If the parameter is NOT required then no error should be returned 

Example Configuration that does not work but should: 
```yaml
delete:
      parameters:
        - in: path
          name: componentType
          schema:
            type: string
          required: true
        - in: query
          name: id
          schema:
            type: string
          required: false
```
