### ISSUE TITLE
As a developer I should be able to create a context value using a parameter value

### ISSUE THREAD

**Issue by akeemphilbert** [wepala/weos#219]
There are times where you want to use the value a user passes in for a parameter, as a value in the context as well (e.g. use a parameter value to setup a list filter via the context). 

```
  /cms/components/{componentType}:
    get:
      operationId: component.list
      summary: See a list of components of a given type
      x-controller: ListComponent
      x-context:
        _filters:
          type:
            eq: ${componentType}
```
